services:
  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx_coming_soon
    labels:
      maintainer: "Arash Hatami <hatamiarash7@gmail.com>"
      org.opencontainers.image.created: ${DATE_CREATED}
      org.opencontainers.image.version: ${APP_VERSION}
      org.opencontainers.image.authors: "hatamiarash7"
      org.opencontainers.image.vendor: "hatamiarash7"
      org.opencontainers.image.title: "Coming Soon"
      org.opencontainers.image.description: "Coming soon template"
      org.opencontainers.image.source: "https://github.com/hatamiarash7/coming-soon"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./config/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "${NGINX_PORT}:80"
    command: ["nginx", "-g", "daemon off;"]
    env_file:
      - .env
